### PR TITLE
HTTPS Support

### PR DESCRIPTION
**Pull request by MTWiley**
- Default "protocol" set to http to try not to break existing implementations.
- Default "ssl_verify"  set to True to encourage the use of valid certificates, but can easily be set to False to work around self signed certs and such.

### CODE REVIEW

**Comment by costastf** [comment]
Thanks for this! I would rather have a flag for the protocol, like secure=true that would set it appropriately instead of accepting it as an argument. Is this something you would like to refactor to?

**Comment by MTWiley** [comment]
@costastf I'm not super familiar with git and how to squash commits.   Are you able to squash and merge to clean this up a bit? Or should I delete this PR/Branch/Fork and then recreate them with a single commit and resubmit a new PR?

**Comment by costastf** [comment]
I think that if you just push your change it will reflect on the pr

**Comment by MTWiley** [comment]
@costastf The change has been pushed to the branch and should be reflected in the PR.   Do you mind taking a look at the changes before I go and update the documentation to reflect the new way of using it?

**Comment by costastf** [comment]
@MTWiley , thanks for the refactoring. Please update the documentation and add yourself to the contributors also. I will accept the PR although the code is not very pythonic and I will refactor it a bit before releasing the new version.I am currently on vacation and I will do that after the 24th. I hope that is ok with you and again thanks for contributing!

**Comment by costastf** [comment]
@MTWiley I am back and looking into this. Are you going to update the documentation accordingly and add yourself to the contributors so I can merge this?

**Comment by MTWiley** [comment]
@costastf Usage Docs and Contributors are updated, let me know if you need/want me to change anything else.

**Comment by costastf** [comment]
No its great, thanks!

**Pull request merged**
