### PR TITLE
Add scm_branch option to JobTemplate.launch()

### PR DESCRIPTION
**Pull request by howardjones**
I had a requirement to launch a job template with non-default SCM branches for testing. The API supports this, but towerlib didn't.

### CODE REVIEW

**Comment by costastf** [comment]
Thanks!

**Comment by costastf** [comment]
version 3.9.2 is uploaded with your change. Thanks again!

**Comment by howardjones** [comment]
Sweet! Thanks for the quick turnaround! I can retire my private wheel already :-)
(also, I love how easy these kinds of changes are to make)

**Comment by costastf** [comment]
I love your enthousiasm :) If i get myself to fix the testing it will be even easier :D

**Pull request merged**
